[rewrite_local]
^https?:\/\/beijing\.ditie\/beijing_subway(?:\?.*)?$ url script-analyze-echo-response https://raw.githubusercontent.com/miracomangomanchuria/jsforfun/main/beijing_subway/beijing_subway_qx.js

[mitm]
hostname = beijing.ditie
